workflow:
    rules:
    - if: $CI_COMMIT_BRANCH != "khaldoun" && $CI_PIPELINE_SOURCE != "merge-request-event" 
      when: never
    - when: always

run_unit_tests:
    tags:
        - local
        - windows
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - "node_modules"
        policy: pull-push
    before_script:
        - npm install
    script:
        - npm run test:report
    artifacts:
        when: always
        paths:
            - ./junit.xml
        reports:
            junit: ./junit.xml
