workflow:
    rules:
    - if: $CI_COMMIT_BRANCH != "khaldoun" && $CI_PIPELINE_SOURCE != "merge-request-event" 
      when: never
    - when: always
stages:
    - clean
    - build
    - test



lint_job:
    stage: clean
    tags: 
        - windows
        - local 
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - "node_modules"
        policy: pull-push
    before_script:
        - npm install
    script:
        - echo "formatting code"
        - npm run format
        - echo "linting code"
        - npm run lint




run_unit_tests:
    image: ubuntu:22.04
    stage: test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    needs:
        - lint_job
    tags:
        - local
        - windows
    before_script:
        - npm install
    script:
        - npm run test:report | grep -E /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        when: always
        paths:
            - ./junit.xml
        reports:
            junit: ./junit.xml

