- hosts: all
  become: true
  become_user: root
  tasks:
    - name: update
      yum:
        name: "*"
        state: latest
    - name: install docker
      yum:
        name: docker
        state: latest
    - name: service docker
      service:
        name: docker
        state: started
        enabled: yes
